import { execFile } from 'child_process';
import { promisify } from 'util';
import { mkdtemp, readdir, readFile, rm } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { YoutubeTranscript } from 'youtube-transcript';

const execFileAsync = promisify(execFile);

const VALID_LANGS = new Set(['ko', 'en', 'en-US', 'ja', 'zh', 'zh-TW', 'es', 'fr', 'de', 'pt']);

export interface TranscriptSegment {
  start: number;
  duration: number;
  text: string;
}

export interface TranscriptResult {
  videoId: string;
  lang: string;
  isAutoGenerated: boolean;
  method: 'ytdlp' | 'npm';
  segments: TranscriptSegment[];
  fullText: string;
}

const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/;

export function extractVideoId(url: string): string | null {
  try {
    const u = new URL(url);
    let id: string | null = null;
    if (u.hostname === 'youtu.be') id = u.pathname.slice(1).split('?')[0] || null;
    else if (u.hostname.includes('youtube.com')) id = u.searchParams.get('v');
    return id && VIDEO_ID_RE.test(id) ? id : null;
  } catch { return null; }
}

export function validateLang(lang: string): string {
  return VALID_LANGS.has(lang) ? lang : 'ko';
}

function getProxyArg(): string | null {
  const raw = process.env.OUTBOUND_CHANNELS || '';
  for (const ch of raw.split(',')) {
    const c = ch.trim();
    if (c.startsWith('socks5://')) return c.replace('socks5://', 'socks5h://');
    if (c.startsWith('http://') || c.startsWith('https://')) return c;
  }
  return null;
}

// json3 포맷: { events: [{ tStartMs, dDurationMs, segs: [{utf8}] }] }
function parseJson3(raw: string): TranscriptSegment[] {
  const data = JSON.parse(raw);
  const segments: TranscriptSegment[] = [];
  for (const event of (data.events ?? [])) {
    if (!event.segs) continue;
    const text = event.segs.map((s: any) => s.utf8 ?? '').join('').replace(/\n/g, ' ').trim();
    if (!text) continue;
    segments.push({
      start: (event.tStartMs ?? 0) / 1000,
      duration: (event.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  return segments;
}

async function fetchViaYtDlp(videoId: string, lang: string): Promise<TranscriptResult> {
  const tmpDir = await mkdtemp(join(tmpdir(), `yt_${videoId}_`));
  try {
    const outputTemplate = join(tmpDir, 'transcript');
    const args = [
      '--write-auto-sub', '--write-sub',
      '--sub-lang', lang,
      '--sub-format', 'json3',
      '--skip-download',
      '--no-warnings',
      '-o', outputTemplate,
      `https://www.youtube.com/watch?v=${videoId}`,
    ];

    const proxy = getProxyArg();
    if (proxy) args.unshift('--proxy', proxy);

    await execFileAsync('yt-dlp', args, { timeout: 30000 });

    const files = await readdir(tmpDir);
    const json3File = files.find(f => f.endsWith('.json3'));
    if (!json3File) throw new Error('자막 파일 없음');

    const raw = await readFile(join(tmpDir, json3File), 'utf-8');
    const isAutoGenerated = json3File.includes('.auto.');
    const segments = parseJson3(raw);
    if (segments.length === 0) throw new Error('자막 세그먼트 없음');

    return {
      videoId,
      lang,
      isAutoGenerated,
      method: 'ytdlp',
      segments,
      fullText: segments.map(s => s.text).join(' '),
    };
  } finally {
    await rm(tmpDir, { recursive: true, force: true });
  }
}

async function fetchViaNpm(videoId: string, lang: string): Promise<TranscriptResult> {
  const items = await YoutubeTranscript.fetchTranscript(videoId, { lang });
  if (!items || items.length === 0) throw new Error('자막 없음');

  const segments: TranscriptSegment[] = items.map(i => ({
    start: i.offset / 1000,
    duration: i.duration / 1000,
    text: i.text.replace(/\n/g, ' ').trim(),
  }));

  return {
    videoId,
    lang,
    isAutoGenerated: true,
    method: 'npm',
    segments,
    fullText: segments.map(s => s.text).join(' '),
  };
}

export async function fetchTranscript(url: string, lang: string): Promise<TranscriptResult> {
  const videoId = extractVideoId(url);
  if (!videoId) throw Object.assign(new Error('유효한 YouTube URL이 아닙니다'), { status: 400 });

  const validLang = validateLang(lang);

  try {
    return await fetchViaYtDlp(videoId, validLang);
  } catch (e1) {
    try {
      return await fetchViaNpm(videoId, validLang);
    } catch (e2) {
      throw Object.assign(
        new Error('자막을 가져올 수 없습니다. 자막이 없거나 비공개 영상일 수 있습니다.'),
        { status: 404 }
      );
    }
  }
}
