[phases.setup]
aptPkgs = ["yt-dlp"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "cp .env.production .next/standalone/.env.production"]

[start]
cmd = "node .next/standalone/server.js"
