[phases.setup]
aptPkgs = ["python3", "ffmpeg"]
cmds = ["curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && chmod a+rx /usr/local/bin/yt-dlp"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "cp .env.production .next/standalone/.env.production"]

[start]
cmd = "node .next/standalone/server.js"
